name: deploy to digital ocean
on: [push]
jobs:
  build:
    name: Build My Hello App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: say hello
        run: ./.github/workspace/scripts/test.sh
