env:
  IMAGE_NAME: "shemsiu/hello"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout master
  #       uses: actions/checkout@v2

  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8

  #     - name: Install dependencies with pipenv
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pipenv
  #         if [ -f Pipfile ]; then pipenv install --deploy --dev; fi

  #     - name: Lint with flake8
  #       run: |
  #         # stop the build if there are Python syntax errors or undefined names
  #         pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  #         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  #         pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  #     - name: Test with pytest
  #       run: |
  #         pipenv run pytest .

  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: shemsiu/hello:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          # KEY: ${{ secrets.SSHKEY }}
          password: ${{ secrets.PASSWORD }}
          envs: IMAGE_NAME
          script: |
            echo $(date) > deployed_at
            # Stop running container
            docker stop $(echo $IMAGE_NAME)

            # Remove old container
            docker rm $(echo $IMAGE_NAME)

            # Run a new container from a new image
            docker run -it -p 9000:9002 $(echo $IMAGE_NAME)

# docker run -d \
# --restart always \
# -p 9000:9002 \
# --name $(echo $IMAGE_NAME)

# docker run -d \
# --restart always \
# -p 9000:9002 \
# --name shemsiu/hello
