name: deploy to digital ocean
on: [push]
jobs:
  build:
    name: Build My Hello App
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo 'Hello World'

      - name: custom script
        run: sh ./scripts/runBash.sh
