name: Run test

env:
  COMMAND: ps

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test command
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.x"
      - run: echo $COMMAND
