name: Run test

env:
  COMMAND: ps

on:
  [push]
  # push:
  # branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.x"
      - run: $(echo $COMMAND)
